//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// VisionTestTool.rc에서 사용되고 있습니다.
//
#define IDD_VISIONTESTTOOL_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     130
#define IDD_DIALOG2                     132
#define IDD_DIALOG_LUT                  137
#define IDD_DIALOG3                     138
#define IDC_TAB1                        1000
#define IDC_STATIC_CAMERA_VIEW          1001
#define IDC_STATIC_RESULT_VIEW          1002
#define IDC_STATIC_GRAPH_VIEW           1003
#define IDC_BTN_BLUR                    1004
#define IDC_BTN_GAUSSIAN_BLUR           1005
#define IDC_BTN_MEDIAN_BLUR             1006
#define IDC_BTN_BILATERAL_BLUR          1007
#define IDC_EDIT_BLUR_SIZE              1008
#define IDC_EDIT_GAUSSIAN_SIZE          1009
#define IDC_EDIT_MEDIAN_SIZE            1010
#define IDC_EDIT_BILATERAL_D            1011
#define IDC_EDIT_BILATERAL_SC           1012
#define IDC_EDIT_BILATERAL_SS           1013
#define IDC_COMBO_MORPH                 1014
#define IDC_BTN_DENOISE                 1015
#define IDC_EDIT_MORPH_SIZE             1016
#define IDC_RADIO_SOBEL_1               1017
#define IDC_CHECK_GET_VIEW_IMAGE        1018
#define IDC_EDIT_DENOISE_TEMPLATE       1019
#define IDC_BTN_MORPH                   1020
#define IDC_STATIC_HISTOGRAM_VIEW       1021
#define IDC_BTN_THRESHOLD               1022
#define IDC_BTN_SHOW_IMAGE              1023
#define IDC_EDIT_THRESHOLD1             1024
#define IDC_BTN_HIST_EQUALIZATION       1025
#define IDC_EDIT_THRESHOLD_2            1026
#define IDC_BTN_HIST_STRETCH            1027
#define IDC_COMBO_THRESHOLD             1028
#define IDC_BTN_WHITE_BALANCE           1029
#define IDC_BTN_ADAPTIVE_THRESH         1030
#define IDC_BTN_CLAHE                   1031
#define IDC_EDIT_ADAP_BLOCK             1032
#define IDC_EDIT_CLIP_LIMIT             1033
#define IDC_EDIT_ADAP_C                 1034
#define IDC_EDIT_TILE_SIZE              1035
#define IDC_EDIT_CANNY1                 1036
#define IDC_EDIT_GAMMA_VALUE            1037
#define IDC_EDIT_CANNY2                 1038
#define IDC_BTN_BGR                     1039
#define IDC_EDIT_HOUGH_CIRCLE_DIST      1040
#define IDC_BUTTON3                     1041
#define IDC_BTN_HSV                     1042
#define IDC_BTN_CANNY                   1043
#define IDC_BTN_RANSAC_LINE             1044
#define IDC_BTN_BAYERTOGRAY             1045
#define IDC_BTN_HOUGH_CIRCLE            1046
#define IDC_BTN_RANSAC_CIRCLE           1047
#define IDC_BTN_GAMMA_CORRECTION        1048
#define IDC_BTN_SOBEL                   1049
#define IDC_BTN_RANSAC_ELLIPSE          1050
#define IDC_BTN_HIST_EQUALIZATION2      1051
#define IDC_BTN_DEHAZE                  1052
#define IDC_EDIT_SOBEL_SIZE             1053
#define IDC_BTN_RETINA                  1053
#define IDC_EDIT_RANSAC_THRESH1         1054
#define IDC_BTN_RETINA2                 1054
#define IDC_BTN_ILLUM                   1054
#define IDC_EDIT_HOUGH_CIRCLE_PARAM1    1055
#define IDC_COMBO_RANSAC_POS            1056
#define IDC_EDIT_HOUGH_CIRCLE_PARAM2    1057
#define IDC_CHECK_RANSAC_CENTER         1058
#define IDC_EDIT_HOUGH_CIRCLE_MIN       1059
#define IDC_EDIT_RANSAC_THRESH2         1060
#define IDC_EDIT_DH_RADIUS              1060
#define IDC_RADIO_SOBEL_2               1061
#define IDC_EDIT_DH_OMEGA               1061
#define IDC_EDIT_RANSAC_SIZE            1062
#define IDC_EDIT_DH_T0                  1062
#define IDC_RADIO_SOBEL_3               1063
#define IDC_EDIT_DH_R                   1063
#define IDC_BTN_RESIZE                  1064
#define IDC_EDIT_DH_EPS                 1064
#define IDC_SLIDER_ROTATE               1065
#define IDC_BTN_TEST                    1066
#define IDC_EDIT_HOUGH_CIRCLE_MAX       1067
#define IDC_BTN_CONTOUR                 1068
#define IDC_EDIT_ROTATE                 1069
#define IDC_BTN_TEST2                   1070
#define IDC_BTN_HOUGH_LINE              1071
#define IDC_EDIT_RESIZE                 1072
#define IDC_EDIT_DENOISE_SEARCH         1073
#define IDC_COMBO_CONTOUR_MODE          1074
#define IDC_EDIT_HOUGH_LINE             1075
#define IDC_COMBO_CONTOUR_METHOD        1076
#define IDC_EDIT_DENOISE_H              1077
#define IDC_BTN_CONVEX_HULL             1078
#define IDC_SLIDER_CANNY1               1079
#define IDC_BTN_WATERSHED               1080
#define IDC_SLIDER_CANNY2               1081
#define IDC_BTN_MATCHING_LOAD_MARK      1082
#define IDC_STATIC_MATCHING_MARK        1083
#define IDC_BTN_TEST3                   1084
#define IDC_BTN_MATCHING_TEMPLATE       1085
#define IDC_SLIDER_GAMMA_VALUE          1086
#define IDC_BTN_INIT_LUT                1087
#define IDC_BTN_APPLY_LUT               1088
#define IDC_STATIC_LUT_GRAPH_VIEW       1089
#define IDC_CHECK_APPLY_LUT             1090
#define IDC_EDIT_THRESH                 1091
#define IDC_EDIT_RESIZE3                1092
#define IDC_EDIT_DIST                   1093
#define IDC_BTN_MATCHING_TEMPLATE2      1094
#define IDC_BTN_MATCHING_EDGE           1095
#define IDC_SLIDER_SH_X                 1096
#define IDC_EDIT_SHIFT_X                1097
#define IDC_BTN_STRING_READ2            1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
